#!/bin/zsh
#

exec find . -name "*rs" -exec rustfmt {} \;
exec cargo +nightly clippy
# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
