.\" meli - meli.conf.examples.5
.\"
.\" Copyright 2024 Manos Pitsidianakis
.\"
.\" This file is part of meli.
.\"
.\" meli is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" meli is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with meli. If not, see <http://www.gnu.org/licenses/>.
.\"
.\" SPDX-License-Identifier: EUPL-1.2 OR GPL-3.0-or-later
.de HorizontalRule
.\"\l'\n(.l\(ru1.25'
.sp
..
.de LiteralStringValue
.Sm
.Po Qo
.Em Li \\$1
.Qc Pc
.Sm
..
.de LiteralStringValueRenders
.LiteralStringValue \\$1
.shift 1
.Bo
.Sm
Rendered as:
.Li r##
.Qo
\\$1
.Qc
.Li ##
.Bc
.Sm
..
.\".Dd November 11, 2022
.Dd November 22, 2024
.Dt MELI.CONF.EXAMPLES 5
.Os
.Sh NAME
.Nm meli.conf.examples
.Nd Example configurations for various mail backends supported by the
.Xr meli 1
terminal e-mail client
.\"
.\"
.\"
.\"
.\"
.\".Sh SYNOPSIS
.\".Pa $XDG_CONFIG_HOME/meli/config.toml
.\".\"
.\".\"
.\".\"
.\".\"
.\".\"
.\".Sh DESCRIPTION
.Sh MAILDIR ACCOUNT
An example configuration:
.\"
.\"
.\"
.Bd -literal
[accounts.account-name]
root_mailbox = "/path/to/root/folder"
format = "Maildir"
listing.index_style = "Compact"
identity="email@example.com"
display_name = "Name"
send_mail = 'msmtp --read-recipients --read-envelope-from'
#send_mail = { hostname = "smtp.example.com", port = 587, auth = { type = "auto", username = "user", password = { type = "command_eval", value = "gpg2 --no-tty -q -d ~/.passwords/user.gpg" } }, security = { type = "STARTTLS" } }

# Set mailbox-specific settings
  [accounts.account-name.mailboxes]
  "INBOX" = { alias="Inbox" } #inline table
  "drafts" = { alias="Drafts" } #inline table
  [accounts.account-name.mailboxes."foobar-devel"] # or a regular table
    ignore = true # don't show notifications for this mailbox
.Ed
.\"
.\"
.\"
.Sh MBOX ACCOUNT
An example configuration:
.\"
.\"
.\"
.Bd -literal
[accounts.account-name]
root_mailbox = "/var/mail/username"
format = "mbox"
listing.index_style = "Compact"
identity="username@hostname.local"
send_mail = '/bin/false'
.Ed
.Sh IMAP ACCOUNT
.Bd -literal
[accounts."account-name"]
root_mailbox = "INBOX"
format = "imap"
server_hostname="mail.example.com"
server_password="pha2hiLohs2eeeish2phaii1We3ood4chakaiv0hien2ahie3m"
server_username="username@example.com"
#server_port="993" # imaps
server_port="143" # STARTTLS
use_starttls=true #optional
send_mail = { hostname = "smtp.example.com", port = 587, auth = { type = "auto", username = "user", password = { type = "command_eval", value = "gpg2 --no-tty -q -d ~/.passwords/user.gpg" } }, security = { type = "STARTTLS" } }
display_name = "Name Name"
identity = "username@example.com"
## show only specific mailboxes:
#subscribed_mailboxes = ["INBOX", "INBOX/Sent", "INBOX/Drafts", "INBOX/Junk"]
.Ed
.Ss Gmail account example
.Bd -literal
[accounts."account-name"]
root_mailbox = '[Gmail]'
format = "imap"
send_mail = { hostname = "smtp.gmail.com", port = 587, auth = { type = "auto", username = "user", password = { type = "command_eval", value = "gpg2 --no-tty -q -d ~/.passwords/user.gpg" } }, security = { type = "STARTTLS" } }
server_hostname='imap.gmail.com'
server_password="password"
server_username="username@gmail.com"
server_port="993"
listing.index_style = "Conversations"
identity = "username@gmail.com"
display_name = "Name Name"
# Gmail auto saves sent mail to Sent folder, so don't duplicate the effort:
composing.store_sent_mail = false
.Ed
.Sh JMAP ACCOUNT
The
.Ic server_url
option must hold the address of the server's session endpoint.
.Bd -literal
[accounts."account-name"]
root_mailbox = "INBOX"
format = "jmap"
send_mail = 'server_submission'
server_url="http://localhost:8080"
server_username="user@hostname.local"
server_password="changeme"
identity = "user@hostname.local"
.Ed
.Ss fastmail.com account example
.Lk https://fastmail.com/ Fastmail
uses the
.Em Bearer token
authentication mechanism, so the option
.Ic use_token
must be enabled:
.Bd -literal
[accounts."fastmail-jmap"]
root_mailbox = "INBOX"
format = "jmap"
server_url="https://api.fastmail.com/jmap/session"
server_username="user@fastmail.com"
server_password="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
use_token=true
identity = "My Name <user@fastmail.com>"
send_mail = "server_submission"
.Ed
.Sh NOTMUCH ACCOUNT
TODO
.Sh NNTP / USENET ACCOUNT
TODO
.Sh SEE ALSO
.Xr meli.conf 5 ,
.Xr meli 1 ,
.Xr meli-themes 5
.Sh AUTHORS
Copyright 2017\(en2024
.An Manos Pitsidianakis Aq Mt manos@pitsidianak.is
.Pp
Released under the GPL, version 3 or greater.
This software carries no warranty of any kind.
.Po
See
.Pa COPYING
for full copyright and warranty notices.
.Pc
.Ss Links
.Bl -item -compact
.It
.Lk https://meli\-email.org "Website"
.It
.Lk https://git.meli\-email.org/meli/meli "Main\ git\ repository\ and\ issue\ tracker"
.It
.Lk https://codeberg.org/meli/meli "Official\ read-only\ git\ mirror\ on\ codeberg.org"
.It
.Lk https://github.com/meli/meli "Official\ read-only\ git\ mirror\ on\ github.com"
.It
.Lk https://crates.io/crates/meli "meli\ crate\ on\ crates.io"
.El
